-- 코드를 입력하세요
SET @HOUR_LIST = -1;
SELECT
(@HOUR_LIST := @HOUR_LIST + 1) AS 'HOUR', 
(SELECT COUNT(DATETIME) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) = @HOUR_LIST) AS 'COUNT'
FROM ANIMAL_OUTS
WHERE @HOUR_LIST < 23
ORDER BY @HOUR_LIST